---
# tasks file for httpd
    - name: Install Apache HTTPD
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure the /var/www/html directory exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

